// <auto-generated />
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(Req2TicketContext))]
    [Migration("20260812135718_AddPasswordHashAndRoles")]
    partial class AddPasswordHashAndRoles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("Domain.Entities.Epic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AccentColor")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<int?>("OwnerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("OwnerId");

                    b.ToTable("Epics");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccentColor = 0,
                            Code = "EPIC-7F3A2B9K",
                            Description = "Login, registro y recuperación de contraseña.",
                            Name = "Autenticación",
                            OwnerId = 1,
                            Priority = 2,
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            AccentColor = 1,
                            Code = "EPIC-M4XQ8T2V",
                            Description = "Columnas configurables y drag & drop.",
                            Name = "Tablero Kanban",
                            OwnerId = 2,
                            Priority = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = 3,
                            AccentColor = 2,
                            Code = "EPIC-9DZP5R3W",
                            Description = "Planificación, capacidad del equipo y cierre de sprint.",
                            Name = "Gestión de sprints",
                            OwnerId = 3,
                            Priority = 2,
                            Status = 1
                        },
                        new
                        {
                            Id = 4,
                            AccentColor = 3,
                            Code = "EPIC-2H6NKY4S",
                            Description = "Alta, edición y estimación en puntos.",
                            Name = "Historias de usuario",
                            OwnerId = 4,
                            Priority = 3,
                            Status = 1
                        },
                        new
                        {
                            Id = 5,
                            AccentColor = 4,
                            Code = "EPIC-QB8V3JM7",
                            Description = "Velocity, burndown y lead time por equipo.",
                            Name = "Panel de métricas",
                            OwnerId = 1,
                            Priority = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = 6,
                            AccentColor = 5,
                            Code = "EPIC-5T9WGX2A",
                            Description = "Avisos por email y centro de notificaciones in-app.",
                            Name = "Notificaciones",
                            OwnerId = 2,
                            Priority = 0,
                            Status = 0
                        },
                        new
                        {
                            Id = 7,
                            AccentColor = 7,
                            Code = "EPIC-3RJ7C4ZP",
                            Description = "Carga de documentos y extracción automática de tickets.",
                            Name = "Importador de requerimientos",
                            OwnerId = 3,
                            Priority = 3,
                            Status = 1
                        },
                        new
                        {
                            Id = 8,
                            AccentColor = 9,
                            Code = "EPIC-K2M5NQ8D",
                            Description = "Tema claro/oscuro con preferencia persistida.",
                            Name = "Modo oscuro",
                            OwnerId = 4,
                            Priority = 0,
                            Status = 2
                        });
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "juan@req2ticket.com",
                            Name = "Juan Cruz",
                            PasswordHash = "$2a$11$OxumkutAnNycObUAp.sI5OR8/FoDacrtay0b2z61feEKJxGR5Tzd6",
                            Role = 5
                        },
                        new
                        {
                            Id = 2,
                            Email = "camila@req2ticket.com",
                            Name = "Camila Rossi",
                            PasswordHash = "$2a$11$9JK.29wC/YYDMPrx/17SzuQXEnij2SgPTrAAVOfG6BWtoBwgtOA5e",
                            Role = 4
                        },
                        new
                        {
                            Id = 3,
                            Email = "martin@req2ticket.com",
                            Name = "Martín Díaz",
                            PasswordHash = "$2a$11$5YLkOMjlsgsrGOqYxhb8s.0V9wC7UKQOn3zrHRH5SZh4oMMIOdt/S",
                            Role = 3
                        },
                        new
                        {
                            Id = 4,
                            Email = "sofia@req2ticket.com",
                            Name = "Sofía Vega",
                            PasswordHash = "$2a$11$LtN.MT4Q48L1DP4qVhzCK.FpO09sg2QRWHfkiFpJxBHqQM21ftqGS",
                            Role = 2
                        });
                });

            modelBuilder.Entity("Domain.Entities.Epic", b =>
                {
                    b.HasOne("Domain.Entities.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Owner");
                });
#pragma warning restore 612, 618
        }
    }
}
