// <auto-generated />
using System;
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(Req2TicketContext))]
    [Migration("20260818211009_AddStorySprintRelation")]
    partial class AddStorySprintRelation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("Domain.Entities.Epic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AccentColor")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<int?>("OwnerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("OwnerId");

                    b.ToTable("Epics");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccentColor = 0,
                            Code = "EPIC-7F3A2B9K",
                            Description = "Login, registro y recuperación de contraseña.",
                            Name = "Autenticación",
                            OwnerId = 1,
                            Priority = 2,
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            AccentColor = 1,
                            Code = "EPIC-M4XQ8T2V",
                            Description = "Columnas configurables y drag & drop.",
                            Name = "Tablero Kanban",
                            OwnerId = 2,
                            Priority = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = 3,
                            AccentColor = 2,
                            Code = "EPIC-9DZP5R3W",
                            Description = "Planificación, capacidad del equipo y cierre de sprint.",
                            Name = "Gestión de sprints",
                            OwnerId = 3,
                            Priority = 2,
                            Status = 1
                        },
                        new
                        {
                            Id = 4,
                            AccentColor = 3,
                            Code = "EPIC-2H6NKY4S",
                            Description = "Alta, edición y estimación en puntos.",
                            Name = "Historias de usuario",
                            OwnerId = 4,
                            Priority = 3,
                            Status = 1
                        },
                        new
                        {
                            Id = 5,
                            AccentColor = 4,
                            Code = "EPIC-QB8V3JM7",
                            Description = "Velocity, burndown y lead time por equipo.",
                            Name = "Panel de métricas",
                            OwnerId = 1,
                            Priority = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = 6,
                            AccentColor = 5,
                            Code = "EPIC-5T9WGX2A",
                            Description = "Avisos por email y centro de notificaciones in-app.",
                            Name = "Notificaciones",
                            OwnerId = 2,
                            Priority = 0,
                            Status = 0
                        },
                        new
                        {
                            Id = 7,
                            AccentColor = 7,
                            Code = "EPIC-3RJ7C4ZP",
                            Description = "Carga de documentos y extracción automática de tickets.",
                            Name = "Importador de requerimientos",
                            OwnerId = 3,
                            Priority = 3,
                            Status = 1
                        },
                        new
                        {
                            Id = 8,
                            AccentColor = 9,
                            Code = "EPIC-K2M5NQ8D",
                            Description = "Tema claro/oscuro con preferencia persistida.",
                            Name = "Modo oscuro",
                            OwnerId = 4,
                            Priority = 0,
                            Status = 2
                        });
                });

            modelBuilder.Entity("Domain.Entities.Sprint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Capacity")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Goal")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Sprints");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 13,
                            EndDate = new DateOnly(2026, 8, 5),
                            Goal = "Cerrar el bloque de autenticación y dejar el listado de facturas en producción.",
                            Name = "Sprint 6",
                            StartDate = new DateOnly(2026, 7, 22),
                            Status = 2
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 34,
                            EndDate = new DateOnly(2026, 8, 19),
                            Goal = "Segundo factor operativo y centro de incidencias abierto a los primeros clientes.",
                            Name = "Sprint 7",
                            StartDate = new DateOnly(2026, 8, 5),
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 30,
                            EndDate = new DateOnly(2026, 9, 2),
                            Goal = "Pagos con tarjeta y panel de administración de cuentas.",
                            Name = "Sprint 8",
                            StartDate = new DateOnly(2026, 8, 19),
                            Status = 0
                        });
                });

            modelBuilder.Entity("Domain.Entities.Story", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AssigneeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("TEXT");

                    b.Property<int>("CriteriaDone")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CriteriaTotal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("EpicId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Points")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SprintId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssigneeId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("EpicId");

                    b.HasIndex("SprintId");

                    b.ToTable("Stories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssigneeId = 1,
                            Code = "STORY-2F8K3M9Q",
                            CriteriaDone = 3,
                            CriteriaTotal = 3,
                            EpicId = 1,
                            Points = 5,
                            Priority = 2,
                            SprintId = 1,
                            Status = 2,
                            Title = "Inicio de sesión con email y contraseña"
                        },
                        new
                        {
                            Id = 2,
                            AssigneeId = 4,
                            Code = "STORY-7H4N2P6R",
                            CriteriaDone = 1,
                            CriteriaTotal = 3,
                            EpicId = 1,
                            Points = 3,
                            Priority = 1,
                            SprintId = 2,
                            Status = 1,
                            Title = "Recuperación de contraseña por email"
                        },
                        new
                        {
                            Id = 3,
                            AssigneeId = 2,
                            Code = "STORY-9D5Q8T3W",
                            CriteriaDone = 0,
                            CriteriaTotal = 4,
                            EpicId = 2,
                            Points = 8,
                            Priority = 1,
                            Status = 0,
                            Title = "Columnas configurables en el tablero"
                        },
                        new
                        {
                            Id = 4,
                            Code = "STORY-3K7V2X5Z",
                            CriteriaDone = 0,
                            CriteriaTotal = 2,
                            EpicId = 2,
                            Points = 8,
                            Priority = 2,
                            SprintId = 3,
                            Status = 0,
                            Title = "Arrastrar y soltar tarjetas entre columnas"
                        },
                        new
                        {
                            Id = 5,
                            AssigneeId = 3,
                            Code = "STORY-5M9R4H2N",
                            CriteriaDone = 2,
                            CriteriaTotal = 3,
                            EpicId = 3,
                            Points = 5,
                            Priority = 2,
                            SprintId = 2,
                            Status = 1,
                            Title = "Planificación de sprint con capacidad del equipo"
                        },
                        new
                        {
                            Id = 6,
                            AssigneeId = 3,
                            Code = "STORY-8P2W6D4K",
                            CriteriaDone = 0,
                            CriteriaTotal = 2,
                            EpicId = 3,
                            Points = 5,
                            Priority = 1,
                            SprintId = 3,
                            Status = 0,
                            Title = "Cierre de sprint con reporte de velocity"
                        },
                        new
                        {
                            Id = 7,
                            AssigneeId = 4,
                            Code = "STORY-4T6Z9M3V",
                            CriteriaDone = 1,
                            CriteriaTotal = 3,
                            EpicId = 4,
                            Points = 3,
                            Priority = 3,
                            SprintId = 2,
                            Status = 1,
                            Title = "Alta de historias con estimación en puntos"
                        },
                        new
                        {
                            Id = 8,
                            AssigneeId = 2,
                            Code = "STORY-6X3H8P5Q",
                            CriteriaDone = 0,
                            CriteriaTotal = 2,
                            EpicId = 4,
                            Points = 2,
                            Priority = 1,
                            Status = 0,
                            Title = "Filtro de historias por responsable y prioridad"
                        },
                        new
                        {
                            Id = 9,
                            AssigneeId = 4,
                            Code = "STORY-2N7K4V9M",
                            CriteriaDone = 2,
                            CriteriaTotal = 2,
                            EpicId = 8,
                            Points = 2,
                            Priority = 0,
                            SprintId = 1,
                            Status = 2,
                            Title = "Persistencia de preferencia de tema claro/oscuro"
                        });
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "juan@req2ticket.com",
                            Name = "Juan Cruz",
                            PasswordHash = "$2a$11$OxumkutAnNycObUAp.sI5OR8/FoDacrtay0b2z61feEKJxGR5Tzd6",
                            Role = 5
                        },
                        new
                        {
                            Id = 2,
                            Email = "camila@req2ticket.com",
                            Name = "Camila Rossi",
                            PasswordHash = "$2a$11$9JK.29wC/YYDMPrx/17SzuQXEnij2SgPTrAAVOfG6BWtoBwgtOA5e",
                            Role = 4
                        },
                        new
                        {
                            Id = 3,
                            Email = "martin@req2ticket.com",
                            Name = "Martín Díaz",
                            PasswordHash = "$2a$11$5YLkOMjlsgsrGOqYxhb8s.0V9wC7UKQOn3zrHRH5SZh4oMMIOdt/S",
                            Role = 3
                        },
                        new
                        {
                            Id = 4,
                            Email = "sofia@req2ticket.com",
                            Name = "Sofía Vega",
                            PasswordHash = "$2a$11$LtN.MT4Q48L1DP4qVhzCK.FpO09sg2QRWHfkiFpJxBHqQM21ftqGS",
                            Role = 2
                        });
                });

            modelBuilder.Entity("Domain.Entities.Epic", b =>
                {
                    b.HasOne("Domain.Entities.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Domain.Entities.Story", b =>
                {
                    b.HasOne("Domain.Entities.User", "Assignee")
                        .WithMany()
                        .HasForeignKey("AssigneeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Domain.Entities.Epic", "Epic")
                        .WithMany()
                        .HasForeignKey("EpicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Sprint", "Sprint")
                        .WithMany()
                        .HasForeignKey("SprintId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Assignee");

                    b.Navigation("Epic");

                    b.Navigation("Sprint");
                });
#pragma warning restore 612, 618
        }
    }
}
